# Copyright (C) 2021 Openwrt.org
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for UUgamebooster
LUCI_DEPENDS:=+kmod-tun +luci-compat +libstdcpp6
LUCI_PKGARCH:=all

PKG_NAME:=luci-app-uugamebooster
PKG_VERSION:=1.1

define Package/$(PKG_NAME)/postinst
#!/bin/sh
if [ -z "$DESTDIR" ] && [ -z "$IPKG_INSTROOT" ]; then
    chmod +x /etc/init.d/uuplugin
fi
endef
include $(TOPDIR)/feeds/luci/luci.mk
# call BuildPackage - OpenWrt buildroot signature
